[bin] fix binaries, be careful when throwing errors

diff --git a/.local/bin/push b/.local/bin/push
--- a/.local/bin/push
+++ b/.local/bin/push
@@ -68,8 +68,8 @@ response="$(
 		--form-string "token=$PUSHOVER_TOKEN" \
 		--form-string "priority=$priority" \
 		--form-string "message=$*" \
-		"https://api.pushover.net/1/messages.json" || error "unable to reach pushover.net"
-)"
+		"https://api.pushover.net/1/messages.json"
+)" || error "unable to reach pushover.net"
 if command grep -q '"user":"invalid"' <<<"$response"; then
 	error "invalid user, please check the environment variable PUSHOVER_USER" 78 # EX_CONFIG
 elif command grep -q '"token":"invalid"' <<<"$response"; then
