[shurl] migrate from Shlink to Chhoto URL

diff --git a/.local/bin/shurl b/.local/bin/shurl
--- a/.local/bin/shurl
+++ b/.local/bin/shurl
@@ -5,7 +5,7 @@
 ################################################################################
 
 _NAME="$(command basename "$0")"
-_HELP_DOC="Shorten the URL using Shlink, a self-hosted URL Shortener.
+_HELP_DOC="Shorten the URL using Chhoto URL, a self-hosted URL Shortener.
 
 Usage:
   $_NAME [options] <url>
@@ -14,7 +14,7 @@ Options:
   -h	Print help.
 
 Environment variables:
-  URL_SHORTENER_API_KEY	https://shlink.io/documentation/api-docs/authentication
+  URL_SHORTENER_AUTH_BASIC
   URL_SHORTENER_URL"
 CURL_ARGS="--connect-timeout 2 --max-time 5"
 SKIP_HTTP_PREFIX='true'
@@ -61,10 +61,9 @@ while getopts ":h" arg; do
 done
 shift $((OPTIND - 1))
 
-[[ -z "$URL_SHORTENER_URL" ]] && error "missing environment variable, please set URL_SHORTENER_URL" 78         # EX_CONFIG
-[[ -z "$URL_SHORTENER_API_KEY" ]] && error "missing environment variable, please set URL_SHORTENER_API_KEY" 78 # EX_CONFIG
-[[ $# -eq 0 ]] && error "missing input, please pass a URL" 64                                                  # EX_USAGE
-[[ $# -gt 1 ]] && error "invalid input, do not pass more than one URL" 64                                      # EX_USAGE
+[[ -z "$URL_SHORTENER_URL" ]] && error "missing environment variable, please set URL_SHORTENER_URL" 78 # EX_CONFIG
+[[ $# -eq 0 ]] && error "missing input, please pass a URL" 64                                          # EX_USAGE
+[[ $# -gt 1 ]] && error "invalid input, do not pass more than one URL" 64                              # EX_USAGE
 url="$1"
 [[ ! $url =~ ^https?://[^\.]+\..+$ ]] && error "invalid input, please pass a URL" 65 # EX_DATAERR
 
@@ -72,17 +71,15 @@ url="$1"
 # Execute.
 ################################################################################
 
+[[ -n $URL_SHORTENER_AUTH_BASIC ]] && curl_auth_arg="-u $URL_SHORTENER_AUTH_BASIC"
 # shellcheck disable=SC2086
 response="$(
 	command curl -qsS $CURL_ARGS \
-		-X POST "$URL_SHORTENER_URL/rest/v3/short-urls" \
-		-H "X-Api-Key: $URL_SHORTENER_API_KEY" \
-		--json '{"longUrl": "'"$url"'", "findIfExists": true}' ||
+		-X POST $curl_auth_arg \
+		-d '{"shortlink": "", "longlink":"'"$url"'"}' "$URL_SHORTENER_URL/api/new" ||
 		error "unable to reach $URL_SHORTENER_URL"
 )"
-command grep -q '"title":"Invalid API key"' <<<"$response" &&
-	error "invalid API key, please check the environment variable URL_SHORTENER_API_KEY"
-response="$(echo "$response" | command tr ',' '\n' | command sed -En 's/.*"shortUrl":"(.*)"/\1/p')"
+response="$URL_SHORTENER_URL/$response"
 [[ -z "$response" ]] && error "unknown error, missing repsonse"
 [[ -n "$SKIP_HTTP_PREFIX" ]] && response="$(command sed -E 's|https?://||g' <<<"$response")"
 echo "$response"
